name: Quarto Publish

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout
        uses: actions/checkout@v3

      # Étape 2 : Installer Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Étape 3 : Installer les packages R nécessaires
      - name: Install R Packages
        run: |
          Rscript -e 'install.packages(c("knitr", "rmarkdown"), repos="https://cloud.r-project.org/")'

      # Étape 4 : Générer le site
      - name: Render Site
        run: quarto render

      # Étape 5 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
