name: Quarto Publish

on:
  push:
    branches:
      - main  # Or the branch where your Quarto project resides

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Step 3: Install R packages (if you use R in your Quarto project)
      - name: Install R Packages
        run: |
          mkdir -p ~/.R/library
          echo 'R_LIBS_USER="~/.R/library"' >> ~/.Renviron
          Rscript -e 'install.packages(c("knitr", "rmarkdown"), repos="https://cloud.r-project.org/")'

      # Step 4: Render the Quarto site
      - name: Render Site
        run: quarto render

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # The directory where Quarto builds the site
